// Patterns that not occur so much and we may need to summon them
const stale = [
  // 'archive',
  // 'squider',
  // 'Catchpoint',
  // 'proxy',
  // 'Protocol',
  // 'Netcraft',
  // 'daum',
  // 'database',
  // 'lyzer',
  // 'preview',
];

export const starters = [
  '^Moz',
  '^Sony',
  '^blackber',
  '^SAMS',
  '^BrightSign',
  '^apple',
  '^Thunderstor',
  '^lyn',
  '^vib',
  '^Lavf',
  '^Xumo',
  '^Oper',
  '^OneBro',
  '^ps4',
  '^mobile',
  '^dalvi',
  '^espn',
  '^linux',
  '^Roku',
  '^Hulu',
];

export const botPatterns = [
  'http(s|:)',
  'bot',
  'Google (F|P)',
  'bingp',
  'Mediapartners',
  'Chrome-Lighthouse',
  'HeadlessChrome',
  '\\.com',
  'crawl',
  'spider',
  'HTTrack',
  'ips-agent',
  'Preview',
  '(PTST\\/(1|2))',
  'DMBrowser',
  'PingdomTMS',
  'DareBoost',
  'zgrab',
  'Java',
  'splash',
  'cloud',
  'Awesomium',
  'Site',
  'evaliant$',
  'DejaClick',
  'PhysicalWeb',
  'burp',
  'GomezAgent',
  'RuxitSynthetic',
  'outbrain',
  'scrap',
  'scan',
  '^Mozilla/5.0libwww',
  'Jeeves\\/Teoma',
];
