export const valid = new Set([
  'gmail.com',
  'yahoo.com',
  'hotmail.com',
  'outlook.com',
  'icloud.com',
  'aol.com',
  'aim.com',
  'gmx.com',
  'gmx.us',
  'mail.com',
  'yandex.com',
  'zoho.com',
  'protonmail.com',
  'protonmail.ch',
  'hey.com',
]);
